---

- name: get libgcrypt
  shell: wget http://ftp.us.debian.org/debian/pool/main/libg/libgcrypt11/libgcrypt11_1.5.0-5+deb7u3_armhf.deb
  args:
    chdir: ~/
  sudo: True

- name: get chromium-browser
  shell: wget http://launchpadlibrarian.net/218525709/chromium-browser_45.0.2454.85-0ubuntu0.14.04.1.1097_armhf.deb
  args:
    chdir: ~/
  sudo: True

- name: get chromium codecs
  shell: wget http://launchpadlibrarian.net/218525711/chromium-codecs-ffmpeg-extra_45.0.2454.85-0ubuntu0.14.04.1.1097_armhf.deb
  args:
    chdir: ~/
  sudo: True

- name: install libgcrypt
  shell: sudo dpkg -i libgcrypt11_1.5.0-5+deb7u3_armhf.deb
  args:
    chdir: ~/
  sudo: True

- name: install codecs
  shell: sudo dpkg -i chromium-codecs-ffmpeg-extra_45.0.2454.85-0ubuntu0.14.04.1.1097_armhf.deb
  args:
    chdir: ~/
  sudo: True

- name: install chromium-browser
  shell: sudo dpkg -i chromium-browser_45.0.2454.85-0ubuntu0.14.04.1.1097_armhf.deb
  args:
    chdir: ~/
  sudo: True