---

- name: Create server directory
  file:
    path: "{{ project_path }}"
    state: directory
    owner: "{{ owner_user }}"
    group: "{{ owner_group }}"

- name: Create media directory
  file:
    path: /data/media
    state: directory
    owner: "{{ owner_user }}"
    group: "{{ owner_group }}"

- name: checkout server project
  git:
    repo: https://github.com/jpitzo/slomedia-server.git
    dest: "{{ project_path }}"
    force: yes

- name: install npm packages
  shell: npm install
  args:
    chdir: "{{ project_path }}"

- name: add sync host
  lineinfile: dest=/etc/hosts line="{{ sync_host }} raspberry_sync"
  sudo: True

- stat: path=/usr/local/bin/evrouter
  register: evrouter

#- include: evrouter.yml
#  when: evrouter.stat.exists == False

- stat: path=/etc/udev/rules.d/powermate.rules
  register: powermate_rules

- name: Copy udev rules
  copy:
    src: ../templates/powermate.rules_j2
    dest: /etc/udev/rules.d/powermate.rules
  sudo: True
  when: powermate_rules.stat.exists == False

- name: Restart udev
  shell: service udev restart
  sudo: True
  when: powermate_rules.stat.exists == False

- name: add upstart  
  template:
    src: ../templates/sloserver.conf_j2
    dest: /etc/init/sloserver.conf
  sudo: True

- name: Check list of Node.js apps running.
  command: forever list
  register: forever_list
  changed_when: false

- name: restart server
  service: name=sloserver state=restarted
  sudo: True
