---

- name: Create server directory
  file:
    path: /data/server
    state: directory
    owner: pi
    group: pi
  sudo: True

- name: checkout server project
  git:
    repo: https://github.com/jpitzo/slomedia-server.git
    dest: /data/server
    force: yes

- name: install npm packages
  shell: npm install
  args:
    chdir: /data/server

- stat: path=/usr/local/bin/evrouter
  register: evrouter

- include: evrouter.yml
  when: evrouter.stat.exists == False

- stat: /etc/udev/rules.d/powermate.rules
  register: powermate_rules

- name: Copy udev rules
  copy:
    src: powermate.rules_j2
    dest: /etc/udev/rules.d/powermate.rules
  sudo: True
  when: powermate_rules.stat.exists == False

- name: Restart udev
  shell: service restart udev
  sudo: True
  when: powermate_rules.stat.exists == False
