---

- name: Create server directory
  file:
    path: "{{ project_path }}"
    state: directory
    owner: vagrant
    group: vagrant

- name: Create media directory
  file:
    path: /data/media
    state: directory
    owner: vagrant
    group: vagrant

- name: checkout server project
  git:
    repo: https://github.com/jpitzo/slomedia-server.git
    dest: "{{ project_path }}"
    force: yes

- name: install npm packages
  shell: npm install
  args:
    chdir: "{{ project_path }}"

- name: add sync host
  lineinfile: dest=/etc/hosts line="{{ sync_host }} raspberry_sync"
  sudo: True

- stat: path=/usr/local/bin/evrouter
  register: evrouter

#- include: evrouter.yml
#  when: evrouter.stat.exists == False

- stat: path=/etc/udev/rules.d/powermate.rules
  register: powermate_rules

- name: Copy udev rules
  copy:
    src: ../templates/powermate.rules_j2
    dest: /etc/udev/rules.d/powermate.rules
  sudo: True
  when: powermate_rules.stat.exists == False

- name: Restart udev
  shell: service udev restart
  sudo: True
  when: powermate_rules.stat.exists == False

- name: Check list of Node.js apps running.
  command: forever list
  register: forever_list
  changed_when: false

#- name: Stop server
#  command: "forever stop {{ project_path }}/server.js"
#  when: "forever_list.stdout.find('{{ project_path }}/server.js') != -1"

- name: Start server.
  command: "forever start {{ project_path }}/server.js"
