---

- name: Create client directory
  file:
    path: /data/client
    state: directory
    owner: www-data
    group: www-data
  sudo: True

- name: checkout client project
  git:
    repo: https://github.com/jpitzo/slomedia-client.git
    dest: /data/client
    force: yes

- name: add web host host
  lineinfile: dest=/etc/hosts line="127.0.0.1 slomedialocal"
  sudo: True

- name: install npm packages
  npm: path=/data/client

- name: install bower packages
  bower: path=/data/client

- name: install ruby packages
  shell: bundle install
  args:
    chdir: /data/client

- name: build project
  shell: grunt build
  args:
    chdir: /data/client

- name: restart nginx
  service: name=nginx state=restarted

#- stat: path=/usr/bin/chromium-browser
#  register: chromium

#- include: chromium.yml
#  when: chromium.stat.exist == False